version: "2.3"
services:
  redis:
    image: hub.c.163.com/library/redis:4.0
    networks:
      sentry-net:
        aliases:
         - redis

  postgres:
    image: hub.c.163.com/library/postgres:9.6
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      sentry-net:
        aliases:
         - postgres

  sentry:
    image: hub.c.163.com/library/sentry:8.20
    ports: 
      - "9000:9000"
    env_file:
      - ./.env
    volumes:
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
        
  sentry-cron:
    image: hub.c.163.com/library/sentry:8.20
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    
  sentry-worker-1:
    image: hub.c.163.com/library/sentry:8.20
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
  sentry-worker-2:
    image: hub.c.163.com/library/sentry:8.20
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net

volumes:
  pgdata:
    driver: local
  sentryfiles:
    driver: local

networks:
  sentry-net:

  