version: "2.3"
services:
  redis:
    image: hub.c.163.com/library/redis:4.0

  postgres:
    image: hub.c.163.com/library/postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data

  sentry:
    image: hub.c.163.com/library/sentry:8.20
    ports: 
      - "9000:9000"
    depends_on:
      - redis
      - postgres

  sentry-cron:
    image: hub.c.163.com/library/sentry:8.20
    depends_on:
      - redis
      - postgres
    
  sentry-worker-1:
    image: hub.c.163.com/library/sentry:8.20
    depends_on:
      - redis
      - postgres
  sentry-worker-2:
    image: hub.c.163.com/library/sentry:8.20
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
    driver: local

  