version: "2.3"
services:
  redis:
    image: hub.c.163.com/library/redis:4.0
    restart: unless-stopped
    networks:
      - sentry-net
       
  postgres:
    image: hub.c.163.com/library/postgres:9.6
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sentry-net

  sentry:
    image: hub.c.163.com/library/sentry:8.20
    restart: unless-stopped
    ports: 
      - "9000:9000"
    env_file:
      - ./.env
    volumes:
      - sentryconf:/etc/sentry
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    ulimits:  
      memlock:
        soft: -1
        hard: -1

      nofile:   # It is important to ensure increased ulimits for nofile and nproc are available for the Elasticsearch containers.
        soft: 65536
        hard: 65536
      nproc: 65535
        
  sentry-cron:
    image: hub.c.163.com/library/sentry:8.20
    restart: unless-stopped
    command: 
      - run
      - cron
    env_file:
      - ./.env
    volumes:
      - sentryconf:/etc/sentry
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    ulimits:  
      memlock:
        soft: -1
        hard: -1

      nofile:   # It is important to ensure increased ulimits for nofile and nproc are available for the Elasticsearch containers.
        soft: 65536
        hard: 65536
      nproc: 65535
    
  sentry-worker-1:
    image: hub.c.163.com/library/sentry:8.20
    restart: unless-stopped
    command:
      - run
      - worker
    env_file:
      - ./.env
    volumes:
      - sentryconf:/etc/sentry
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    ulimits:  
      memlock:
        soft: -1
        hard: -1

      nofile:   # It is important to ensure increased ulimits for nofile and nproc are available for the Elasticsearch containers.
        soft: 65536
        hard: 65536
      nproc: 65535
  sentry-worker-2:
    image: hub.c.163.com/library/sentry:8.20
    restart: unless-stopped
    command:
      - run
      - worker
    env_file:
      - ./.env
    volumes:
      - sentryconf:/etc/sentry
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    ulimits:  
      memlock:
        soft: -1
        hard: -1

      nofile:   # It is important to ensure increased ulimits for nofile and nproc are available for the Elasticsearch containers.
        soft: 65536
        hard: 65536
      nproc: 65535
  sentry-worker-3:
    image: hub.c.163.com/library/sentry:8.20
    restart: unless-stopped
    command:
      - run
      - worker
    env_file:
      - ./.env
    volumes:
      - sentryconf:/etc/sentry
      - sentryfiles:/var/lib/sentry/files
    depends_on:
      - redis
      - postgres
    networks:
      - sentry-net
    ulimits:  
      memlock:
        soft: -1
        hard: -1

      nofile:   # It is important to ensure increased ulimits for nofile and nproc are available for the Elasticsearch containers.
        soft: 65536
        hard: 65536
      nproc: 65535

volumes:
  pgdata:
    driver: local
  sentryfiles:
    driver: local
  sentryconf:
    driver: local

networks:
  sentry-net:

  